config/routes.rb
Rails.application.routes.draw do
  # root 'users#index'
  root 'users#home'

  resources :tickets

  resources :tasks
  get "tasks/new" => "tasks#new"
  get "tasks/:id/edit" => "tasks#edit"
  post "tasks/create" => "tasks#create"
  post "tasks/:id/update" => "tasks#update"
  post "tasks/:id/destroy" => "tasks#destroy"


  resources :users  
  #get 'users/index'
  get 'users/home'  
  get "/" => "users#home"   
  post "users/:id/destroy" => "users#destroy"
  get "users/:id/tickets" => "users#tickets"
  get "users/:id/today" => "users#today"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  resources :users do
    resources :tasks
    resources :tickets
  end

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :users, optional: true
  has_many :tickets, dependent: :destroy  
  validates :t_title, presence: true,
            length: { maximum: 255 } 
  default_scope -> { order(created_at: :desc) }
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
    @tasks = Task.order('updated_at DESC')
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show  
    session[:task_id] = @task.id 
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create 
    @task = Task.new(task_params)
    @task.user_id = session[:user_id]     
    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
      #if @task.update(t_title: params[:t_title], t_descn: params[:t_descn])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      #format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.html { redirect_to user_path(@task.user_id), notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      #params.require(:task).permit(:t_title, :t_descn, :user_id, :ticket_ids)   
      params.require(:task).permit(:t_title, :t_descn)    
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<div class="main posts-new">
  <div class="container">
    <!-- h1 class="form-heading">Create a new task</h1 -->
    <h1 class="form-heading">Task</h1>
    <div class="post-user-name"> 
      <% if @task.id %>
        <%= link_to 'Back to Task', task_path(@task.id) %> 
      <% else %>      
        <%= link_to 'Back to User', "/users/#{session[:user_id]}" %>
      <% end %>
    </div>
    <%= form_with(model: task, local: true) do |form|%>    
      <div class="form">
        <div class="form-body">
          <% @task.errors.full_messages.each do |message| %>
            <div class="form-error">
              <%= message %>
            </div>
          <% end %>
          <p><%= form.label :Task %></p>
          <%= form.text_field :t_title %> 
          <p><%= form.label :Description %></p>              
          <%= form.text_area :t_descn %>
          <%= form.submit %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/_task.html.erb
<%= link_to task.user.name, task.user %>
<p><%= task.t_title %> </p>
<p><%= task.t_descn %> </p>
<p>Created <%= time_ago_in_words (task.created_at) %> ago </p>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back to Task', @task %> |
<%#= link_to 'Back to Tasks', tasks_path %> |
<%= link_to 'Back to User', user_path(@task.user_id) %> 

app/views/tasks/index.html.erb
<% provide(:title, "Tasks") %>

<div class="main users-index">
<div class="container">
<h1 class="users-heading">Tasks</h1>
<%#= link_to 'New Task', new_task_path %>

<table>
  <thead>
    <tr>
      <th width="150px" align="left">Task</th>
      <th width="250px" align="left">Description</th>
      <th width="150px" align="left">Updated</th>
      <th width="30px" align="left">user_id</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= link_to task.t_title, task %></td>
        <td><%= task.t_descn.first(50) %></td>
        <td><%= task.updated_at.localtime.strftime("%Y.%m.%d, %H:%M") %></td>
        <td><%= task.user_id %></td>
        <!-- <td width="30px"><%= link_to 'Show', task %></td> 
        <td width="30px"><%= link_to 'Edit', edit_task_path(task) %></td>
        <td width="30px"><%= link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      -->
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%#= link_to 'Back to Tasks', tasks_path %>
<%#= link_to 'Back to All users', users_path %> 
<%#= link_to 'Back to User', user_path(@task.user_id) %> 

app/views/tasks/show.html copy.erb
<% provide(:title, "Task") %>
  
<h1><%= current_user.name %></h1>
<%#= @task.user_id %>
<br></br>

<div>
  <strong>TASK:</strong> &ensp; 
  <strong><%= @task.t_title %></strong>
</div>
<br></br>
<div>
  <strong >DESCRIPTION:</strong>
  <p class="desc"><%= @task.t_descn %></p>
</div>

<table >
<td class="butt"><%= button_to 'EDIT TASK', edit_task_path(@task), method: :get%></td>
<td class="butt"><%= link_to 'Delete Task', @task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</table>

<%#= link_to 'Edit Task', edit_task_path(@task) %> 
<%#= link_to 'Back to All users', users_path %> 
<%= link_to 'Back to User', user_path(@task.user_id) %> 

app/views/tasks/show.html.erb
<% provide(:title, "Task") %>
<div class="main posts-show">
  <div class="container">
    <div class="post-user-name">
      <!--  <img src="<%#= "/user_images/#{@user.image_name}" %>">  -->        
      <%#= link_to(@user.name, "/users/#{@user.id}") %>
      <h1><%= link_to current_user.name, user_path(@task.user_id) %> </h1>
      <h3>Task</h3>
    </div>    
    <div class="posts-show-item">
    
      <h3><%= @task.t_title %></h3>
      <p><%= @task.t_descn %></p>
      
      <div class="post-time">
        <%= @task.updated_at.localtime.strftime("%Y.%m.%d, %H:%M")%>
      </div>

      <%# if @task.user_id == @current_user.id %>
        <div class="post-menus">        
          <%= link_to("Edit", "/tasks/#{@task.id}/edit") %>|          
          <%#= link_to("Delete", "/tasks/#{@task.id}/destroy", {method: "post"}) %> <!--no confirmation -->
          <%= link_to 'Delete', @task, method: :delete, data: { confirm: 'Are you sure?' } %> |
          <%= link_to 'New Ticket', new_ticket_path %> 
        </div>
      <%# end %>                  
    </div>
    
    <br></br>
    <h3>Tickets</h3>
    <% @task.tickets.each do |ticket| %> 
      <div class="users-index-item">
        <!-- <div class="user-right"> -->
          <%= link_to ticket.ticket_d.first(50), ticket %>
          <div class="post-time">
            Last update: <%= ticket.updated_at.localtime.strftime("%Y.%m.%d, %H:%M")%> </p> 
          </div>
          <%#= link_to("Edit", "/tickets/#{ticket.id}/edit") %> 
          <div class="post-menus"> 
            <%= link_to 'Edit', edit_ticket_path(ticket) %> |
            <%#= link_to 'Back', tickets_path %> 
            <%#= link_to 'Back to User', user_path(@ticket.user_id) %> 
            <%= link_to 'Delete', ticket, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>           
        <!-- </div> -->
      </div>
    <% end %>     
  </div>
</div>