config/routes.rb
Rails.application.routes.draw do
  # root 'users#index'
  root 'users#home'

  resources :tickets

  resources :tasks
  get "tasks/new" => "tasks#new"
  get "tasks/:id/edit" => "tasks#edit"
  post "tasks/create" => "tasks#create"
  post "tasks/:id/update" => "tasks#update"
  post "tasks/:id/destroy" => "tasks#destroy"


  resources :users  
  #get 'users/index'
  get 'users/home'  
  get "/" => "users#home"   
  post "users/:id/destroy" => "users#destroy"
  get "users/:id/tickets" => "users#tickets"
  get "users/:id/today" => "users#today"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  resources :users do
    resources :tasks
    resources :tickets
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy
  has_many :tickets, dependent: :destroy
  validates :name, presence: true, 
            uniqueness: true, 
            length: { maximum: 50 }
  
  #has_many :tickets, through: :tasks, dependent: :destroy  # Show only Tickets for User's Tasks

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :tickets, :today]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    @users = User.order('name') 
    @task = Task.all
    @ticket = Ticket.all
  end

  def home
    session[:user_id] = nil
    session[:task_id] = nil
    @users = User.all
    @user = User.find_by(id: params[:id])
    @users = User.order('name')
  end

  # GET /users/1
  # GET /users/1.json
  def show
    session[:task_id] = nil
    @user = User.find(params[:id])    
    @task = @user.tasks
    @tasks = @task.order('updated_at DESC')
    @ticket = @user.tickets
    @tickets = @ticket.order('updated_at')
    session[:user_id] = @user.id
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find_by(id: params[:id])
    @user.destroy
    flash[:notice] = "User successfully deleted"
    redirect_to("/")
  end

  def tickets
    @tickets = Ticket.order('updated_at')
  end

  def today
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])      
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :active_job, :time, :task_ids, :ticket_ids)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html copy.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="new">
    <%= form.label :name %>
    <%= form.text_field :name %>
    
    <%#= form.label :task %>
    <%#= form.text_field :active_job %>
    
    <%#= form.label :time %>
    <%#= form.text_field :time %>  
    <%#= form.label :added_at %>        
    <%#= Time.now.strftime("%H:%M %B %d,%Y") %>
  
    <br></br>
  
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="main posts-new">
  <div class="container">
    <h1 class="form-heading">Create a new User</h1>
    <%= form_with(model: user, local: true) do |form| %>
      <div class="form">
        <div class="form-body">
          <% @user.errors.full_messages.each do |message| %>
            <div class="form-error">
              <%= message %>
            </div>
          <% end %>
          <p><%= form.label :User_name %></p>
          <%= form.text_field :name %>   
          <%#= form.label :task %>
          <%#= form.text_field :active_job %>    
          <%#= form.label :time %>
          <%#= form.text_field :time %>  
          <%#= form.label :added_at %>        
          <%#= Time.now.strftime("%H:%M %B %d,%Y") %>  
          <%= form.submit %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>
<p><%= link_to 'Delete User', @user, method: :delete, data: { confirm: 'Are you sure?' } %></p>
<br></br>
<%= button_to 'Back to User', user_path, method: :get%>

<%#= link_to 'Back to User', @user %> 
<%#= link_to 'Back', users_path %>

app/views/users/home.html.erb
<div class="main users-index">
  <div class="container">
    <h1 class="users-heading">All Users</h1>
    <% @users.each do |user| %>
      <div class="users-index-item">
        <div class="user-right">
          <!-- Link to the "User details" page -->
          <%= link_to(user.name, "/users/#{user.id}") %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "Users") %>

<p id="notice"><%= notice %></p>

<h1>Users</h1>

<p><%= button_to 'NEW USER', new_user_path, method: :get%>
</p>

<table>
  <thead>
    <tr>
      <th width="200px" align="left">Name</th>
      <th width="200px" align="left">Active task</th>
      <th width="150px" align="left">Task updated</th>
     
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user%></td>
        <td> <%# user.tasks.last(1).each do |u| %>
        <% user.tasks.order('updated_at DESC').take(1).each do |u| %>
          <%= link_to u.t_title, u %>: 
          <%= u.t_descn.first(50) %>
        <% end %>  
        </td>
        <td> <%# user.tasks.last(1).each do |u| %>
        <% user.tasks.order('updated_at DESC').take(1).each do |u| %>
          <%= u.updated_at.localtime.strftime("%H:%M %Y.%m.%d")%> 
        <% end %>
        </td> 
      </tr>
    <% end %>
  </tbody>
</table>

<br></br>

<%#= tasks = User.all.map { |u| u.tasks.last } %>

<%#= button_to 'NEW USER', new_user_path, method: :get%>
<%#= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%#= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% provide(:title, "User") %>
<div class="main user-show">
  <div class="container">
    <div class="user">
      <h2><%= @user.name %></h2>             
      <%= link_to("Edit","/users/#{@user.id}/edit") %> |      
      <%#= link_to("Delete","/users/#{@user.id}/destroy", {method: "post"}) %>
      <%= link_to 'Delete', @user, method: :delete, data: { confirm: 'Are you sure?' } %> |
      <%= link_to 'New Task', new_task_path %>     
    </div>  

    <ul class="user-tabs">
      <li class="active"><%= link_to("Tasks", "/users/#{@user.id}") %></li>
      <li><%= link_to("Tickets", "/users/#{@user.id}/tickets") %></li>
      <li><%= link_to("Today", "/users/#{@user.id}/today") %></li>
    </ul>

    <% @user.tasks.each do |a| %>        
      <div class="posts-index-item">
        <div class="post-right"> 
          <div class="post-user-name">              
            <p><%= link_to a.t_title, a %></p>
          </div>          
          <p><%= a.t_descn.first(100) %></p>
          <div class="post-time">
            <p>Last update: <%= a.updated_at.localtime.strftime(" %Y.%m.%d, %H:%M")%></p> 
          </div>
        </div>
      </div>
    <% end %> 

  </div>
</div>

app/views/users/tickets.html.erb
<% provide(:title, "User") %>
<div class="main user-show">
  <div class="container">
    <div class="user">
      <h2><%= @user.name %></h2>             
      <%= link_to("Edit","/users/#{@user.id}/edit") %> |      
      <%#= link_to("Delete","/users/#{@user.id}/destroy", {method: "post"}) %>
      <%= link_to 'Delete', @user, method: :delete, data: { confirm: 'Are you sure?' } %> |
      <%= link_to 'New Task', new_task_path %>     
    </div>  

    <ul class="user-tabs">
      <li><%= link_to("Tasks", "/users/#{@user.id}") %></li>
      <li class="active"><%= link_to("Tickets", "/users/#{@user.id}/tickets") %></li>
      <li><%= link_to("Today", "/users/#{@user.id}/today") %></li>
    </ul>
   
   <% @user.tickets.each do |ticket| %> 
      <div class="users-index-item">
        <!-- <div class="user-right"> -->
        <div class="tickets-left">
          <%= link_to ticket.ticket_d.first(50), ticket %>
          <div class="post-time">
            Last update: <%= ticket.updated_at.localtime.strftime("%Y.%m.%d, %H:%M")%> </p> 
          </div>
          </div>
          <%#= link_to("Edit", "/tickets/#{ticket.id}/edit") %> 
          <div class="post-menus"> 
            <%= link_to 'Edit', edit_ticket_path(ticket) %> |
            <%#= link_to 'Back', tickets_path %> 
            <%#= link_to 'Back to User', user_path(@ticket.user_id) %> 
            <%= link_to 'Delete', ticket, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>           
        <!-- </div> -->
      </div>
    <% end %>   
    
  </div> 
</div> 

app/views/users/today.html.erb
<% provide(:title, "User") %>
<div class="main user-show">
  <div class="container">
    <div class="user">
      <h2><%= @user.name %></h2>             
      <%= link_to("Edit","/users/#{@user.id}/edit") %> |      
      <%#= link_to("Delete","/users/#{@user.id}/destroy", {method: "post"}) %>
      <%= link_to 'Delete', @user, method: :delete, data: { confirm: 'Are you sure?' } %> |
      <%= link_to 'New Task', new_task_path %>     
    </div>  

    <ul class="user-tabs">
      <li><%= link_to("Tasks", "/users/#{@user.id}") %></li>
      <li><%= link_to("Tickets", "/users/#{@user.id}/tickets") %></li>
      <li class="active"><%= link_to("Today", "/users/#{@user.id}/today") %></li>
    </ul>
   
  
    
  </div> 
</div> 