config/routes.rb
Rails.application.routes.draw do
  # root 'users#index'
  root 'users#home'

  resources :tickets

  resources :tasks
  get "tasks/new" => "tasks#new"
  get "tasks/:id/edit" => "tasks#edit"
  post "tasks/create" => "tasks#create"
  post "tasks/:id/update" => "tasks#update"
  post "tasks/:id/destroy" => "tasks#destroy"


  resources :users  
  #get 'users/index'
  get 'users/home'  
  get "/" => "users#home"   
  post "users/:id/destroy" => "users#destroy"
  get "users/:id/tickets" => "users#tickets"
  get "users/:id/today" => "users#today"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  resources :users do
    resources :tasks
    resources :tickets
  end

end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  belongs_to :task, optional: true 
  validates :task_id, presence: true
  validates :ticket_d, presence: true,
            length: { maximum: 1000 } 
  default_scope -> { order(created_at: :desc) }
  
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    #@ticket = Ticket.find_by(task_id:params[:task_id])     
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
    @task = Task.new
    @user = User.new
  end

  # GET /tickets/1/edit
  def edit   
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.user_id = session[:user_id] 
    @ticket.task_id = session[:task_id]
    #@user = User.find(user_id: params[:user_id]) 
    #@user = User.find(params[:user_id])    #work   
    #@ticket = @user.tickets.build(ticket_params)
    # @user = User.find(params[:user_id]) # Error "User Must Exist" if has_many :tickets, through: :tasks    
    # @user = Task.find_by(user_id:params[:task_id]) # Do not work
    # @user = Task.find_by(user_id:params[:user_id]) # Error
    # @ticket = @user.tasks.create(ticket_params) # Error    
    # @ticket = Ticket.find_by(task_id:params[:task_id]) 

  if @ticket.save
    flash[:notice] = "Ticket successfully created"    
    redirect_to("/tasks/#{@ticket.task_id}")
  else
    render("tickets/new")
  end
end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy    
    @ticket.destroy
    respond_to do |format|
      #format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }      
      format.html { redirect_to user_path(@ticket.user_id), notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ticket_params
      params.require(:ticket).permit(:ticket_d, :ticket_start, :ticket_end)
      #params.require(:ticket).permit(:ticket_d, :ticket_start, :ticket_end, :user_id)
      #params.require(:ticket).permit(:ticket_d, :ticket_start, :ticket_end, :user_id, task_id)
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html copy.erb
<%= form_with(model: ticket, local: true) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
        <% ticket.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :User_id %>
    <%#= form.text_field :user_id %>
    <%= form.collection_select :user_id, User.all, :id, :name, {:prompt => '-- Select a User --'} %>
  </div>

  <div class="field">
    <%= form.label :Task_id %>
    <%#= form.text_field :task_id %>
    <%= form.collection_select :task_id, Task.all, :id, :t_title, {:prompt => '-- Select a Task --'} %>
    <%#= form.collection_select :task_id, @user.tasks, :id, :t_title, {:prompt => '-- Select a Task --'} %>
  </div>

  <div class="field">
    <%= form.label :Description %>
    <%= form.text_area :ticket_d, rows: 10, cols: 50 %>
  </div>

  <div>
    <p><%= form.label :ticket_start %></p>
    <p><%= form.time_select :ticket_start %></p>
    <p><%= form.date_select :ticket_start %></p>    
  </div>
  
  <div width="150x">
    <p><%= form.label :ticket_end %></p>
    <p><%= form.time_select :ticket_end %></p>
    <p><%= form.date_select :ticket_end %></p>
    
  </div>
  <br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tickets/_form.html.erb
<div class="main posts-new">
  <div class="container">
    <h1 class="form-heading">Ticket</h1>
    <div class="post-user-name"> 
    <% if @ticket.id %>
      <%= link_to 'Back to ticket', ticket_path(@ticket.id) %> 
    <% else %>      
      <%= link_to 'Back to task', "/tasks/#{session[:task_id]}" %>
    <% end %>
    </div>
    <%= form_with(model: ticket, local: true) do |form| %>
      <div class="form">
      <div class="form-body">
        <% if ticket.errors.any? %>
          <div class="form-error">
            <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>
            <ul><% ticket.errors.full_messages.each do |message| %>        
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div class="field">
          <%= form.label :Description %>
          <%= form.text_area :ticket_d %>
        </div>
        <div>
         <p><%= form.label :ticket_start %></p>
         <p><%= form.time_select :ticket_start %></p>
         <p><%= form.date_select :ticket_start %></p> 
         </div>  
        <div width="150x">
          <p><%= form.label :ticket_end %></p>
          <p><%= form.time_select :ticket_end %></p>
          <p><%= form.date_select :ticket_end %></p>    
        </div>         
        <%= form.submit %>
       </div>
     </div>
    <% end %>
  </div>
</div>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%#= link_to 'Back', tickets_path %>
<%= link_to 'Back to User', user_path(@ticket.user_id) %> 

app/views/tickets/index.html.erb
<% provide(:title, "Tickets") %>

<div class="main users-index">
<div class="container">
<h1 class="users-heading">Tickets</h1>
<%#= link_to 'New Ticket', new_ticket_path %>
<table>
  <thead>
    <tr>
      
      <th width="300px" align="left">Description</th>
      <th width="150px" align="left">Updated</th>
      <!--<th align="left">Start</th>
      <th align="left">End</th>-->
      <th width="150px" align="left">user_id</th>
      <th width="150px" align="left">task_id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr> 
        <td><%= link_to ticket.ticket_d.first(50), ticket %></td>
        <td><%= ticket.updated_at.localtime.strftime("%H:%M %Y.%m.%d") %></td>
        <!-- 
        <td><%= ticket.ticket_start.localtime.strftime("%H:%M %Y.%m.%d") %></td>          
        <td><%= ticket.ticket_end.localtime.strftime("%H:%M %Y.%m.%d") %></td>
        -->
        <td><%= ticket.user_id %></td>
        <td><%= ticket.task_id %></td>
        <!-- 
        <td width="30px"><%#= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        -->
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<% provide(:title, "Ticket") %>

<div class="main posts-show">
  <div class="container">
    <div class="post-user-name">      
     <h1><%#= link_to @ticket.task_id, task_path(@ticket.task_id) %> 
     <%#= link_to current_user.name, user_path(@task.user_id) %> </h1>    
    <%= link_to 'Back to task', task_path(@ticket.task_id) %> 
    </div> 
    <div class="posts-show-item">       
      <%= @ticket.ticket_d %>
      <div class="post-time">
      <p>
        <strong>Started at: </strong><%= @ticket.ticket_start.strftime("%H:%M %Y.%m.%d") %>
        </p> 
        <p>
        <strong>Finished at: </strong><%= @ticket.ticket_end.strftime("%H:%M %Y.%m.%d") %>
        </p>
        <!-- <p>
        <strong>user_id:</strong>
          <%#= @ticket.user_id %>
        </p> 
        <p>
        <strong>task_id:</strong>
          <%#= @ticket.task_id %>
        </p> -->
        <div class="post-menus"> 
          <%= link_to 'Edit', edit_ticket_path(@ticket) %> |
          <%#= link_to 'Back', tickets_path %> 
          <%#= link_to 'Back to User', user_path(@ticket.user_id) %> 
          <%= link_to 'Delete', @ticket, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    </div>    
  </div>
</div>